### ISSUE TITLE
need quotes in solarized-mate.sh

### ISSUE THREAD

**Issue by russkrayer** [oz123/solarized-mate-terminal#6]
It was not working for me until I noticed test was complaining about too many arguments.
This change fixed it for me (sorry if the following is not formatted properly, I simply put double quotes around ${PROFILES} in the if statement around line 14):

```
diff --git a/solarized-mate.sh b/solarized-mate.sh
index 517bb9f..8d8a3a6 100755
--- a/solarized-mate.sh
+++ b/solarized-mate.sh
@@ -11,7 +11,7 @@ fi
 # read profiles as string
 PROFILES=`dconf read /org/mate/terminal/global/profile-list`
 # add new profiles
-if [ -z ${PROFILES} ]; then
+if [ -z "${PROFILES}" ]; then
        PROFILES="['default','solarized-dark', 'solarized-light']"
 else
 echo "f    "
```

**Comment by oz123** [comment]
Can you please use `git` to format a patch propely or fork the repo and make a PR?

**Comment by oz123** [comment]
@russkrayer , thanks !
