### ISSUE TITLE
Error when running bash solarized-mate.sh - with pre-existing profiles

### ISSUE THREAD

**Issue by Aaranaw** [oz123/solarized-mate-terminal#7]
Hi, when running bash solarized-mate.sh I get the following error

~/solarized-mate-terminal$ bash solarized-mate.sh
/usr/bin/dconf
error: 24:expected ',' or ']' to follow array element

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

Terminal must be restarted

**Comment by oz123** [comment]
```
[4] oznt@yeni2:~/Software/solarized-mate-terminal  [master]  $ bash solarized-mate.sh 
/usr/bin/dconf
Terminal must be restarted
[5] oznt@yeni2:~/Software/solarized-mate-terminal  [master]  $ date
Mon Jul 18 12:46:38 CEST 2016
```
It works on a later version of bash ...

Please post here the following information:
```
[6] oznt@yeni2:~/Software/solarized-mate-terminal  [master]  $ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
```

**Comment by Aaranaw** [comment]
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by oz123** [comment]
can you run the script with `bash -x solarized-mate-terminal` and post the output here? Which OS are you using ?

**Comment by Aaranaw** [comment]
Did you mean run solarized-mate.sh ?

`scag@lin-scag:~/solarized-mate-terminal$ bash -x solarized-mate-terminal
bash: solarized-mate-terminal: No such file or directory
scag@lin-scag:~/solarized-mate-terminal$ bash -x solarized-mate.sh
+ which dconf
/usr/bin/dconf
+ [[ '' == \-\-\r\e\s\e\t ]]
++ dconf read /org/mate/terminal/global/profile-list
+ PROFILES='['\''default'\'', '\''profile0'\'']'
+ '[' -z '['\''default'\'', '\''profile0'\'']' ']'
+ [[ ['default', 'profile0'] =~ solarized-dark ]]
+ [[ ['default', 'profile0'] =~ solarized-light ]]
+ M=''\''solarized-dark'\'', '\''solarized-light'\'']'
+ PROFILES='['\''default'\'', '\''profile0, '\''solarized-dark'\'', '\''solarized-light'\'']'
+ dconf write /org/mate/terminal/global/profile-list '['\''default'\'', '\''profile0, '\''solarized-dark'\'', '\''solarized-light'\'']'
error: 24:expected ',' or ']' to follow array element

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

++ cat colors/palette
+ COLORS='#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3'
++ cat colors/base03
+ BGCOLOR='#070736364242'
++ cat colors/base1
+ BOLDCOLOR='#9393a1a1a1a1'
++ cat colors/base0
+ FGCOLOR='#838394949696'
+ PROFILE=solarized-dark
+ dconf write /org/mate/terminal/profiles/solarized-dark/use-theme-colors false
+ dconf write /org/mate/terminal/profiles/solarized-dark/palette '"#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"'
+ dconf write /org/mate/terminal/profiles/solarized-dark/bold-color-same-as-fg false
+ dconf write /org/mate/terminal/profiles/solarized-dark/background-color '"#070736364242"'
+ dconf write /org/mate/terminal/profiles/solarized-dark/foreground-color '"#838394949696"'
+ dconf write /org/mate/terminal/profiles/solarized-dark/bold-color '"#9393a1a1a1a1"'
+ dconf write /org/mate/terminal/profiles/solarized-dark/visible-name '"solarized-dark"'
++ cat colors/base3
+ BGCOLOR='#fdfdf6f6e3e3'
++ cat colors/base00
+ FGCOLOR='#65657b7b8383'
+ PROFILE=solarized-light
+ dconf write /org/mate/terminal/profiles/solarized-light/use-theme-colors false
+ dconf write /org/mate/terminal/profiles/solarized-light/palette '"#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"'
+ dconf write /org/mate/terminal/profiles/solarized-light/bold-color-same-as-fg false
+ dconf write /org/mate/terminal/profiles/solarized-light/background-color '"#fdfdf6f6e3e3"'
+ dconf write /org/mate/terminal/profiles/solarized-light/foreground-color '"#65657b7b8383"'
+ dconf write /org/mate/terminal/profiles/solarized-light/bold-color '"#9393a1a1a1a1"'
+ dconf write /org/mate/terminal/profiles/solarized-light/visible-name '"solarized-light"'
+ echo -e '\e[37;41mTerminal must be restarted\e[0m'
Terminal must be restarted
`

**Comment by oz123** [comment]
please format the code part properly ...

**Comment by oz123** [comment]
I managed to reproduce this bug. This is because you have your own predefined profiles.

```
 $ bash solarized-mate.sh 
/usr/bin/dconf
error: 24:expected ',' or ']' to follow array element

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

Terminal must be restarted
```
